START TRANSACTION;
USE academia;
COMMIT;
START TRANSACTION;
CREATE TABLE IF NOT EXISTS AGENDAMENTOS(
  id                 BIGINT  NOT NULL AUTO_INCREMENT,
  id_localizacao     BIGINT NOT NULL,
  dias_semana       VARCHAR(166) NOT NULL,
  horario             VARCHAR(166) NOT NULL,
  FOREIGN KEY (id_localizacao) REFERENCES LOCALIZACOES(id),
  PRIMARY KEY(id)
);
COMMIT;